version: '3.1'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: ${VPATH}/mariadb
      o: bind
      type: none
  wordpress-data:
    driver: local
    driver_opts:
      device: ${VPATH}/wordpress
      o: bind
      type: none